# Generated by Django 4.2.6 on 2023-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djambda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
